# Site settings
title: 睿法生物
description: > # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog/
url: "rafabio.com" # the base hostname & protocol for your site
author: Copyright &copy; Rafabio
lang: en_US

# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
  
